routes = [
    {
        "name": "Route A",
        "asset": "USDC",
        "network": "Base",
        "cost": 12.00,
        "risk": 10,
        "time_minutes": 2,
        "compliance": "ALLOWED",
        "geopolitical_status": "RESTRICTED",
    },
    {
        "name": "Route B",
        "asset": "BTC",
        "network": "Bitcoin",
        "cost": 25.00,
        "risk": 35,
        "time_minutes": 10,
        "compliance": "ALLOWED",
        "geopolitical_status": "PERMITTED",
    },
    {
        "name": "Route C",
        "asset": "ETH",
        "network": "Ethereum",
        "cost": 8.00,
        "risk": 20,
        "time_minutes": 5,
        "compliance": "BLOCKED",
        "geopolitical_status": "PERMITTED",
    },
    {
        "name": "Route D",
        "asset": "USDT",
        "network": "Ethereum",
        "cost": 8.00,
        "risk": 20,
        "time_minutes": 5,
        "compliance": "PASSED",
        "geopolitical_status": "UNKNOWN",
    },
]
